// MARK: - StabilityModels.swift

// Factory for Stability AI model configurations.

import Foundation

/// Factory enum for creating Stability AI model configurations.
public enum StabilityModels {
    /// Creates all Stability AI model configurations.
    public static func createModels() -> [ProviderModelData] {
        [
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_ULTRA,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Ultra",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "576x1024",
                        "1024x576",
                        "1344x576",
                        "576x1344",
                        "1536x1024",
                        "1024x1536",
                        "1280x1024",
                        "1024x1280",
                    ],
                    supportedVariants: [
                        "default",
                        "enhance",
                        "photographic",
                        "anime",
                        "digital-art",
                        "comic-book",
                        "fantasy-art",
                        "line-art",
                        "analog-film",
                        "neon-punk",
                        "isometric",
                        "low-poly",
                        "origami",
                        "modeling-compound",
                        "cinematic",
                        "3d-model",
                        "pixel-art",
                        "tile-texture",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/ultra",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1ultra/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_CORE,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Core",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "576x1024",
                        "1024x576",
                        "1344x576",
                        "576x1344",
                        "1536x1024",
                        "1024x1536",
                        "1280x1024",
                        "1024x1280",
                    ],
                    supportedVariants: [
                        "default",
                        "enhance",
                        "photographic",
                        "anime",
                        "digital-art",
                        "comic-book",
                        "fantasy-art",
                        "line-art",
                        "analog-film",
                        "neon-punk",
                        "isometric",
                        "low-poly",
                        "origami",
                        "modeling-compound",
                        "cinematic",
                        "3d-model",
                        "pixel-art",
                        "tile-texture",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/core",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1core/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SDXL,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable XL 1.0 (SDXL)",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "1152x896",
                        "896x1152",
                        "1216x832",
                        "1344x768",
                        "768x1344",
                        "1536x640",
                        "640x1536",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/SDXL-and-SD1.6",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SD3,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable 3.0 Large",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "576x1024",
                        "1024x576",
                        "1344x576",
                        "576x1344",
                        "1536x1024",
                        "1024x1536",
                        "1280x1024",
                        "1024x1280",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelDeprecationDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: false
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SD3_TURBO,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable 3.0 Turbo",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "576x1024",
                        "1024x576",
                        "1344x576",
                        "576x1344",
                        "1536x1024",
                        "1024x1536",
                        "1280x1024",
                        "1024x1280",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelDeprecationDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: false
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SD35_LARGE,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable 3.5 Large",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "576x1024",
                        "1024x576",
                        "1344x576",
                        "576x1344",
                        "1536x1024",
                        "1024x1536",
                        "1280x1024",
                        "1024x1280",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SD35_LARGE_TURBO,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable 3.5 Large Turbo",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "576x1024",
                        "1024x576",
                        "1344x576",
                        "576x1344",
                        "1536x1024",
                        "1024x1536",
                        "1280x1024",
                        "1024x1280",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SD35_MEDIUM,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable 3.5 Medium",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "576x1024",
                        "1024x576",
                        "1344x576",
                        "576x1344",
                        "1536x1024",
                        "1024x1536",
                        "1280x1024",
                        "1024x1280",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SD35_FLASH,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable 3.5 Flash",
                modelDescription: "Generate polished images from written prompts.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxPromptLength: 4096,
                    supportedDimensions: [
                        "1024x1024",
                        "576x1024",
                        "1024x576",
                        "1344x576",
                        "576x1344",
                        "1536x1024",
                        "1024x1536",
                        "1280x1024",
                        "1024x1280",
                    ],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2024-10-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1sd3/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_CREATIVE_UPSCALE,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Creative Upscale",
                modelDescription: "Enhance image detail while preserving creative intent.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 1_048_576,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportsNegativePrompt: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/upscale/creative",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Upscale/paths/~1v2beta~1stable-image~1upscale~1creative/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_CONSERVATIVE_UPSCALE,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Conservative Upscale",
                modelDescription: "Enhance image detail while preserving creative intent.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 9_437_184,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportsNegativePrompt: true,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/upscale/conservative",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Upscale/paths/~1v2beta~1stable-image~1upscale~1conservative/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_FAST_UPSCALE,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Fast Upscale",
                modelDescription: "Enhance image detail while preserving creative intent.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 1_048_576,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportsPrompt: false,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2024-01-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/upscale/fast",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Upscale",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_ERASE,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Erase",
                modelDescription: "Edit masked image areas with prompt guidance.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 9_437_184,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportsMask: true,
                    supportsNegativePrompt: true,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/erase",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1erase/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_INPAINT,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Inpaint",
                modelDescription: "Edit masked image areas with prompt guidance.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 9_437_184,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportsMask: true,
                    supportsNegativePrompt: true,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/inpaint",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1inpaint/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_OUTPAINT,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Outpaint",
                modelDescription: "Extend images beyond their original frame.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 9_437_184,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportsExpandDirections: true,
                    supportsNegativePrompt: true,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/outpaint",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1outpaint/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SEARCH_AND_REPLACE,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Search and Replace",
                modelDescription: "Replace selected image details with prompt guidance.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 9_437_184,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportsNegativePrompt: true,
                    supportsSearchPrompt: true,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/search-and-replace",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1search-and-replace/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_SEARCH_AND_RECOLOR,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Search and Recolor",
                modelDescription: "Recolor selected image areas with prompt guidance.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 9_437_184,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 10000,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportedGrowMaskRange: IntRange(0, 20),
                    supportedVariants: [
                        "default",
                        "enhance",
                        "photographic",
                        "anime",
                        "digital-art",
                        "comic-book",
                        "fantasy-art",
                        "line-art",
                        "analog-film",
                        "neon-punk",
                        "isometric",
                        "low-poly",
                        "origami",
                        "modeling-compound",
                        "cinematic",
                        "3d-model",
                        "pixel-art",
                        "tile-texture",
                    ],
                    supportsNegativePrompt: true,
                    supportsSearchPrompt: true,
                    supportsSeed: true,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2024-01-01"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/search-and-recolor",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_REMOVE_BACKGROUND,
                modelSetType: EnumSetType.IMAGE_GENERATE,
                modelName: "Stable Remove Background",
                modelDescription: "Remove image backgrounds for product-ready visuals.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImagePixels: 4_194_304,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["1024x1024", "576x1024", "1024x576", "768x1024", "1024x768"],
                    supportsPrompt: false,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/stable-image/edit/remove-background",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Edit/paths/~1v2beta~1stable-image~1edit~1remove-background/post",
                active: true
            ),
            ProviderModelData(
                providerId: EnumProviderCode.STABILITY_AI.providerId,
                modelCode: EnumProviderModelCode.STABILITY_IMAGE_TO_VIDEO,
                modelSetType: EnumSetType.VIDEO_GENERATE,
                modelName: "Stable Image to Video",
                modelDescription: "Animate still images into motion clips.",
                modelParams: ModelParams(
                    maxGenerations: 6,
                    maxImageSizeBytes: 10 * 1024 * 1024,
                    maxPromptLength: 4096,
                    supportedDimensions: ["768x768", "576x1024", "1024x576"],
                    supportedMotionRange: DoubleRange(15, 255),
                    supportedStickynessRange: DoubleRange(0, 10),
                    supportedVideoDurations: [4],
                    supportsNegativePrompt: true,
                    supportsSourceImage: true
                ),
                modelLaunchDate: getDateFromString("2023-07-26"),
                modelGenerateBaseURL: "https://api.stability.ai/v2beta/image-to-video",
                modelAPIDocumentationURL: "https://platform.stability.ai/docs/api-reference#tag/Image-to-Video",
                active: false
            ),
        ]
    }
}
